version: '3.7'
services:
  moodle:
    image: moodlehq/moodle-php-apache:8.1
    ports:
      - "8080:80"
    environment:
      - MOODLE_DOCKER_DBTYPE=mariadb
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodlepass
    volumes:
      - ./moodlehtml:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - db

  db:
    ports:
     - '3306:3306'
    image: mariadb:11.3
    ports:
     - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=moodlepass
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepass
    volumes:
      - ./dbdata:/var/lib/mysql
