version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.4.0  # Last stable version with working proxy
    container_name: grafana_dashboard
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - compose_toolbank-network

networks:
  compose_toolbank-network:
    external: true

volumes:
  grafana_storage:
    driver: local
