# This is a Databricks asset bundle definition for Learning Management System Academy.
# The Databricks extension requires databricks.yml configuration file.
# See https://docs.databricks.com/dev-tools/bundles/index.html for documentation.

bundle:
  name: Learning Management System Academy

targets:
  dev:
    mode: development
    default: true
    workspace:
      host: https://dbc-b975c647-8055.cloud.databricks.com

  ## Optionally, there could be 'staging' or 'prod' targets here.
  #
  # prod:
  #   workspace:
  #     host: https://dbc-b975c647-8055.cloud.databricks.com
